add_newline = true

format = """
$directory$git_branch$git_status
$character
"""

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = ""
style = "bold yellow"

[git_status]
style = "bold green"

[character]
success_symbol = "[❯](bold white)"
error_symbol = "[❯](bold red)"

[cmd_duration]
disabled = true

[time]
disabled = true

[battery]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[docker_context]
disabled = true

[kubernetes]
disabled = true

[hostname]
disabled = true

[username]
disabled = true

[os]
disabled = true
